global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'prometheus-docker'
rule_files:
  - "alert.rules_nodes"
  - "alert.rules_tasks"
  - "alert.rules_service-groups"
scrape_configs:
- job_name: 'prometheus'
  dns_sd_configs:
  - names:
    - 'tasks.prometheus'
    type: 'A'
    port: 9090
#- job_name: 'kafka_exporter'
#  dns_sd_configs:
#  - names:
#    - 'tasks.kafka_exporter'
#    type: 'A'
#    port: 9308
#- job_name: 'kafka_exporter'
#  static_configs:
#  - targets:
#    - docker.for.mac.localhost:9308
# JMX agents    
#- job_name: 'kafka'
#  static_configs:
#  - targets:
#    - docker.for.mac.localhost:7071
#    - docker.for.mac.localhost:7072
#    - docker.for.mac.localhost:7073
- job_name: 'apps'
  scrape_interval: 5s
  metrics_path: '/metrics'
  static_configs:
  - targets:
    - docker.for.mac.localhost:8080
  basic_auth:
    username: devops
    password: uaepass