---
- name: Converge
  hosts: localhost
  vars:
    docker_host: localhost:2375
  tasks:
    - name: Ensure docker-compose packages are there
      pip:
        name: docker_compose
    - name: Ensure docker-volume packages are presented
      pip:
        name: docker_volume
    - name: "Print working directory"
      debug:
        msg: "Ansible directory with {{ playbook_dir }}"
    - name: Ensure Grafana volume is created
      docker_volume:
        name: grf-data
    - name: "Stop docker compose"
      docker_compose:
        project_src: ../
        docker_host: '{{ docker_host }}'
        files: docker-compose-grf.yml
        state: absent
    - name: "Run docker compose"
      docker_compose:
        project_src: ../ 
        docker_host: '{{ docker_host }}'
        files: docker-compose-grf.yml
      register: output
    - name: Print message output
      debug:
        var: output
    - name: assert that it is running
      assert:
        that: 
          - "grafana.gpl_grafana_1.state.running"
          - "prometheus.gpl_prometheus_1.state.running"
          - "loki.gpl_loki_1.state.running"
          - "jaeger.gpl_jaeger_1.state.running"
