---
- name: Converge
  hosts: localhost
  vars:
    docker_host: localhost:2375
  tasks:
    - name: Check if docker-compose packages are there
      pip:
        name: docker_compose
    - name: "Print working directory"
      debug:
        msg: "Ansible directory with {{ playbook_dir }}"
    - name: Recursively find /tmp files older than 4 weeks and equal or greater than 1 megabyte
      find:
        paths: "/tmp"
        pattern: '*'
        recurse: yes
    - name: "Stop docker compose"
      docker_compose:
        project_src: ../
        docker_host: '{{ docker_host }}'
        files: docker-compose-grf.yml
        state: absent
    - name: "Run docker compose"
      docker_compose:
        project_src: ../ 
        docker_host: '{{ docker_host }}'
        files: docker-compose-grf.yml
      register: output
    - name: Print message output
      debug:
        var: output
    - name: assert that it is running
      assert:
        that: 
          - "grafana.gpl_grafana_1.state.running"
          - "prometheus.gpl_prometheus_1.state.running"
          - "loki.gpl_loki_1.state.running"
          - "jaeger.gpl_jaeger_1.state.running"
